# Traitement des données

Importation des modules

In [2]:
!pip install xlrd

Requirement already satisfied: xlrd in c:\users\sonex\anaconda3\lib\site-packages (2.0.2)

In [3]:
import pandas as pd  
import numpy as np, pandas as pd, matplotlib as plt
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import spearmanr, chi2_contingency
from scipy.stats.contingency import association
from scipy.stats import mannwhitneyu, norm
import chardet
import unicodedata

## Importation des bases de données

In [4]:

# USAGERS impliqués dans l'accident
base_us = pd.read_csv("usagers-2021.csv", delimiter=",", low_memory=False)

In [5]:
# Charger le fichier qui décrit les informations du véhicule des usagers
base_veh = pd.read_csv("vehicules-2021.csv", delimiter=";", encoding="latin1", low_memory=False)

In [6]:
# Charger le fichier qui décrit les circonstances générales de l’accident
base_car = pd.read_excel("caracteristiques.xlsx")

In [7]:
# Charger le fichier qui décrit les lieux de l'accident
base_lieux = pd.read_excel("lieux-2021.xls")

# Analyse et traitement des bases de données

## Analayse de la base des caracteristiques

In [8]:
base_car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56530 entries, 0 to 56529
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Num_Acc  56530 non-null  int64
 1   jour     56530 non-null  int64
 2   mois     56530 non-null  int64
 3   an       56530 non-null  int64
 4   hrmn     56530 non-null  object
 5   lum      56530 non-null  int64
 6   com      56530 non-null  object
 7   agg      56530 non-null  int64
 8   int      56530 non-null  int64
 9   atm      56530 non-null  int64
 10  col      56530 non-null  int64
 11  adr      55957 non-null  object
 12  lat      56530 non-null  object
 13  long     56530 non-null  object
dtypes: int64(9), object(5)
memory usage: 6.0+ MB

In [9]:
print(" la base des caracteristiques contient", sum(base_car.duplicated('Num_Acc')), "doublons")

 la base des caracteristiques contient 11 doublons

In [10]:
#pour compter les doublon pur/parfaits
print("la base des caracteristiques contient", sum(base_car.duplicated()),'doublon purs')

la base des caracteristiques contient 11 doublon purs

In [11]:
# Identifier les lignes dupliquées
duplicated = base_car[base_car.duplicated( keep=False)]
# Trier les lignes dupliquées par ordre croissant de 'Num_Acc'
duplicated = duplicated.sort_values(by='Num_Acc')
# Afficher les lignes dupliquées triées
duplicated

,Num_Acc,jour,mois,an,hrmn,lum,com,agg,int,atm,col,adr,lat,long
33687,202100013498,12,10,2021,11:00,1,CC_71076,2,2,1,3,Avenue de Paris,"46,79438402","4,848719001"
6317,202100013498,12,10,2021,11:00,1,CC_71076,2,2,1,3,Avenue de Paris,"46,79438402","4,848719001"
25206,202100017917,21,9,2021,09:45,1,CC_95280,2,1,1,3,RD 47A,"49,01144865","2,479454682"
19025,202100017917,21,9,2021,09:45,1,CC_95280,2,1,1,3,RD 47A,"49,01144865","2,479454682"
32639,202100023406,19,8,2021,10:00,1,CC_97120,2,1,1,6,UNIVERSITE FOUILLOLE,"16,22706","-61,52962"
420,202100023406,19,8,2021,10:00,1,CC_97120,2,1,1,6,UNIVERSITE FOUILLOLE,"16,22706","-61,52962"
45121,202100027321,23,7,2021,11:10,1,CC_97302,2,1,1,3,A.HENRI(RUE),"4,922661236","-52,3113595"
50662,202100027321,23,7,2021,11:10,1,CC_97302,2,1,1,3,A.HENRI(RUE),"4,922661236","-52,3113595"
2994,202100027995,20,7,2021,18:20,1,CC_62307,2,1,1,1,Route de Peuplingues,"50,914111","1,724478"
55470,202100027995,20,7,2021,18:20,1,CC_62307,2,1,1,1,Route de Peuplingues,"50,914111","1,724478"
7554,202100032369,25,6,2021,17:00,1,CC_43191,1,1,1,7,A75,"45,359021","3,280535"
40541,202100032369,25,6,2021,17:00,1,CC_43191,1,1,1,7,A75,"45,359021","3,280535"
25962,202100034484,15,6,2021,08:40,1,CC_44014,1,3,1,3,Le Gros Caillou,"47,112035","-1,476181"
41559,202100034484,15,6,2021,08:40,1,CC_44014,1,3,1,3,Le Gros Caillou,"47,112035","-1,476181"
20493,202100045186,4,4,2021,19:25,1,CC_49321,1,1,1,6,A11 pk 296+492,"47,427173","-0,930727"
1588,202100045186,4,4,2021,19:25,1,CC_49321,1,1,1,6,A11 pk 296+492,"47,427173","-0,930727"
45931,202100049552,2,3,2021,07:00,2,CC_61256,1,1,1,7,a 88 PK 010+100,"48,663536","0,06772"
8475,202100049552,2,3,2021,07:00,2,CC_61256,1,1,1,7,a 88 PK 010+100,"48,663536","0,06772"
17470,202100051453,15,2,2021,08:40,1,CC_75113,2,1,8,7,AVENUE D IVRY,"48,824631","2,363093"
51196,202100051453,15,2,2021,08:40,1,CC_75113,2,1,8,7,AVENUE D IVRY,"48,824631","2,363093"
17015,202100052300,2,2,2021,13:35,1,CC_74281,2,1,2,6,CORNICHE (BD DE LA) INFERIEUR N°20,"46,37226","6,4741"
29819,202100052300,2,2,2021,13:35,1,CC_74281,2,1,2,6,CORNICHE (BD DE LA) INFERIEUR N°20,"46,37226","6,4741"

In [12]:
base_car = base_car.drop_duplicates(subset='Num_Acc', keep='first')
base_car

,Num_Acc,jour,mois,an,hrmn,lum,com,agg,int,atm,col,adr,lat,long
0,202100037733,28,5,2021,14:15,1,CC_97407,2,2,1,3,JEAN MOULIN (RUE) - RIV. DES GALETS,"-20,95888","55,31743"
1,202100049382,2,3,2021,10:59,1,CC_63113,2,1,1,2,SAINT ROBERT (RUE),"45,79137","3,1162"
2,202100038891,20,5,2021,16:50,1,CC_88160,2,2,1,1,POISSOMPRE (FG DE),"48,18261","6,47218"
3,202100028616,14,7,2021,19:45,1,CC_80021,2,1,1,3,CAGNARD (RUE),"49,90355","2,2872"
4,202100033509,17,6,2021,23:40,3,CC_13214,2,1,1,1,A7-Sens Lyon vers Marseille,"43,34031","5,37689"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56525,202100026753,28,7,2021,17:10,1,CC_38474,2,2,1,3,Rue du Vinay,"45,204957","5,667561"
56526,202100019814,10,9,2021,06:15,3,CC_77251,1,1,1,7,RN 104,"48,631","2,533"
56527,202100016048,29,9,2021,08:15,1,CC_78524,1,1,1,3,A13,"48,841059","2,106997"
56528,202100039830,15,5,2021,06:45,2,CC_13212,2,2,1,3,PIERRE CHEVALIER (avenue),"43,2953","5,4254"
56529,202100046742,13,3,2021,09:30,1,CC_76108,2,1,2,7,HAIE. RUE DE LA,"49,46523106","1,112713775"

## Analyse de la base usagers

In [13]:
base_us.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 129189 entries, 0 to 129188
Data columns (total 15 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Num_Acc      129189 non-null  int64
 1   id_vehicule  129189 non-null  object
 2   num_veh      129189 non-null  object
 3   place        129189 non-null  int64
 4   catu         129189 non-null  int64
 5   grav         129189 non-null  int64
 6   sexe         129189 non-null  int64
 7   an_nais      126122 non-null  float64
 8   trajet       129189 non-null  int64
 9   secu1        129189 non-null  int64
 10  secu2        129189 non-null  int64
 11  secu3        129189 non-null  int64
 12  locp         129189 non-null  int64
 13  actp         129189 non-null  object
 14  etatp        129189 non-null  int64
dtypes: float64(1), int64(11), object(3)
memory usage: 14.8+ MB

In [14]:
print("la base des usagers contient", sum(base_us.duplicated('Num_Acc')), "doublons")

la base des usagers contient 72668 doublons

In [15]:
#pour compter les doublon pur/parfaits
print("la base des usagers contient", sum(base_us.duplicated()),'doublons purs')

la base des usagers contient 33 doublons purs

In [16]:
base_us = base_us.drop_duplicates( keep='first')
base_us

,Num_Acc,id_vehicule,num_veh,place,catu,grav,sexe,an_nais,trajet,secu1,secu2,secu3,locp,actp,etatp
0,202100021165,163Â 830,A01,9,2,4,1,1948.0,0,1,-1,-1,0,0,-1
1,202100020281,165Â 383,A01,1,1,1,2,1965.0,1,1,8,-1,-1,-1,-1
2,202100047336,117Â 153,A01,1,1,4,2,1972.0,0,2,0,-1,-1,-1,-1
3,202100008918,185Â 779,B01,1,1,4,1,1985.0,9,8,0,-1,-1,-1,-1
4,202100009175,185Â 315,A01,1,1,3,1,1960.0,5,1,-1,-1,0,0,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129184,202100018230,169Â 018,D01,1,1,1,2,1982.0,5,1,-1,-1,0,0,-1
129185,202100050268,111Â 866,B01,2,2,4,2,1942.0,1,1,-1,-1,0,0,-1
129186,202100056519,163Â 830,A01,9,2,4,1,1948.0,0,1,-1,-1,0,0,-1
129187,202100056520,165Â 383,A01,1,1,1,2,1965.0,1,1,8,-1,-1,-1,-1
129188,202100056521,117Â 153,A01,1,1,4,2,1972.0,0,2,0,-1,-1,-1,-1

In [17]:
#pour compter les doublon pur/parfaits
print("la base des usagers contient", sum(base_us.duplicated()),'doublon purs')

la base des usagers contient 0 doublon purs

In [18]:
base_us.sort_values(by="Num_Acc", ascending=True).head(10)

,Num_Acc,id_vehicule,num_veh,place,catu,grav,sexe,an_nais,trajet,secu1,secu2,secu3,locp,actp,etatp
24992,202100000001,201Â 765,A01,1,1,1,1,1978.0,1,1,-1,-1,0,0,-1
32123,202100000001,201Â 764,B01,1,1,3,1,2000.0,1,0,9,-1,0,0,-1
45309,202100000002,201Â 762,A01,1,1,4,1,1983.0,0,1,-1,-1,0,0,-1
14610,202100000002,201Â 763,B01,1,1,3,1,1993.0,0,1,-1,-1,0,0,-1
88804,202100000003,201Â 761,A01,10,3,3,2,1959.0,4,0,-1,-1,3,3,1
23858,202100000003,201Â 761,A01,1,1,1,1,1995.0,1,1,0,-1,0,0,-1
113992,202100000004,201Â 759,D01,1,1,2,2,2014.0,5,0,-1,-1,-1,-1,-1
104179,202100000004,201Â 758,A01,1,1,1,1,2000.0,-1,-1,0,-1,-1,-1,-1
53845,202100000005,201Â 755,Z01,1,1,-1,-1,NaN,-1,8,-1,-1,-1,-1,-1
89513,202100000005,201Â 754,A01,1,1,4,2,1997.0,1,1,-1,-1,-1,-1,-1

## Analyse au niveau de la base du Véhicule

In [19]:
base_veh.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97365 entries, 0 to 97364
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ï»¿id_vehicule  97365 non-null  object
 1   num_veh         97365 non-null  object
 2   senc            97365 non-null  int64
 3   catv            97365 non-null  int64
 4   obs             97365 non-null  int64
 5   obsm            97365 non-null  int64
 6   choc            97365 non-null  int64
 7   manv            97365 non-null  int64
 8   motor           97365 non-null  int64
 9   occutc          744 non-null    float64
dtypes: float64(1), int64(7), object(2)
memory usage: 7.4+ MB

In [20]:
# Supprimer les caractères spéciaux des noms de colonnes
base_veh.columns = base_veh.columns.str.encode('ascii', 'ignore').str.decode('ascii')

In [21]:
print(base_veh["occutc"].describe())  # Statistiques descriptives de la variable occutc (Nombre d’occupants dans le transport en commun)
print("Nombre de valeurs manquantes :", base_veh["occutc"].isna().sum())  # Compte les NaN
missing_percentage = base_veh["occutc"].isna().mean() * 100
print(f"Pourcentage de valeurs manquantes : {missing_percentage:.2f}%")

count    744.000000
mean       1.653226
std        1.951130
min        0.000000
25%        1.000000
50%        1.000000
75%        2.000000
max       28.000000
Name: occutc, dtype: float64
Nombre de valeurs manquantes : 96621
Pourcentage de valeurs manquantes : 99.24%

In [22]:
print(" la base des caracteristiques contient", sum(base_veh.duplicated('id_vehicule')), "doublons")

 la base des caracteristiques contient 0 doublons

In [23]:
#pour compter les doublon pur/parfaits
print("la base des usagers contient", sum(base_veh.duplicated()),'doublons purs')

la base des usagers contient 0 doublons purs

## Analyse de base de données des lieux

In [24]:
base_lieux.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56525 entries, 0 to 56524
Data columns (total 19 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Num_Acc  56525 non-null  int64
 1   dep      56525 non-null  object
 2   catr     56525 non-null  int64
 3   voie     52117 non-null  object
 4   v1       56525 non-null  int64
 5   v2       4990 non-null   object
 6   circ     56525 non-null  int64
 7   nbv      56525 non-null  int64
 8   vosp     56525 non-null  int64
 9   prof     56525 non-null  int64
 10  pr       56525 non-null  int64
 11  pr1      56525 non-null  int64
 12  plan     56525 non-null  int64
 13  lartpc   108 non-null    float64
 14  larrout  56525 non-null  float64
 15  surf     56525 non-null  int64
 16  infra    56525 non-null  int64
 17  situ     56525 non-null  int64
 18  vma      56525 non-null  int64
dtypes: float64(2), int64(14), object(3)
memory usage: 8.2+ MB

In [25]:
print(" la base des caracteristiques contient", sum(base_lieux.duplicated('Num_Acc')), "doublons")

 la base des caracteristiques contient 7 doublons

In [26]:
#pour compter les doublons purs/parfaits
print("la base des usagers contient", sum(base_lieux.duplicated()),'doublons purs')

la base des usagers contient 0 doublons purs

# Fusion des bases de données

In [27]:
print(base_us[['id_vehicule', 'num_veh']].drop_duplicates().head())
print(base_veh[['id_vehicule', 'num_veh']].drop_duplicates().head())

  id_vehicule num_veh
0    163Â 830     A01
1    165Â 383     A01
2    117Â 153     A01
3    185Â 779     B01
4    185Â 315     A01
  id_vehicule num_veh
0    129åÊ983     A01
1    192åÊ850     B01
2    152åÊ776     A01
3    193åÊ398     A01
4    178åÊ605     A01

In [28]:
def clean_string(s):
    if isinstance(s, str):
        s = unicodedata.normalize('NFKD', s)  # décompose les caractères accentués
        s = s.encode('ascii', 'ignore').decode('ascii')  # supprime tout ce qui n'est pas ASCII
        return s.strip()
    return s

# Appliquer sur les colonnes des deux bases
for df in [base_us, base_veh]:
    df['id_vehicule'] = df['id_vehicule'].astype(str).apply(clean_string)
    df['num_veh'] = df['num_veh'].astype(str).apply(clean_string)

base_veh["id_vehicule"] = base_veh["id_vehicule"].str.replace("aE", "A ")

In [29]:
# Fusion base_us et base_veh
us_veh = base_us.merge(base_veh, on=['id_vehicule', 'num_veh'], how='left')

# Fusion avec base_car
us_veh_car = us_veh.merge(base_car, on='Num_Acc', how='left')

# Fusion avec base_lieux
base_final = us_veh_car.merge(base_lieux, on='Num_Acc', how='left')

In [30]:
# Compter le nombre d’usagers par accident 
usager_counts = base_us.groupby("Num_Acc").size().reset_index(name="nb_usagers")
usager_counts

            Num_Acc  nb_usagers
0      202100000001           2
1      202100000002           2
2      202100000003           2
3      202100000004           2
4      202100000005           2
...             ...         ...
56516  202100056517           1
56517  202100056518           2
56518  202100056519           1
56519  202100056520           1
56520  202100056521           1

[56521 rows x 2 columns]

In [31]:
base_final= base_final.merge(usager_counts, on="Num_Acc", how="left")

# Analyse et traitement de la base finale

In [32]:
base_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 129169 entries, 0 to 129168
Data columns (total 55 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Num_Acc      129169 non-null  int64
 1   id_vehicule  129169 non-null  object
 2   num_veh      129169 non-null  object
 3   place        129169 non-null  int64
 4   catu         129169 non-null  int64
 5   grav         129169 non-null  int64
 6   sexe         129169 non-null  int64
 7   an_nais      126102 non-null  float64
 8   trajet       129169 non-null  int64
 9   secu1        129169 non-null  int64
 10  secu2        129169 non-null  int64
 11  secu3        129169 non-null  int64
 12  locp         129169 non-null  int64
 13  actp         129169 non-null  object
 14  etatp        129169 non-null  int64
 15  senc         129169 non-null  int64
 16  catv         129169 non-null  int64
 17  obs          129169 non-null  int64
 18  obsm         129169 non-null  int64
 19  choc         129169 non-null  int64
 20  manv         129169 non-null  int64
 21  motor        129169 non-null  int64
 22  occutc       1355 non-null    float64
 23  jour         129166 non-null  float64
 24  mois         129166 non-null  float64
 25  an           129166 non-null  float64
 26  hrmn         129166 non-null  object
 27  lum          129166 non-null  float64
 28  com          129166 non-null  object
 29  agg          129166 non-null  float64
 30  int          129166 non-null  float64
 31  atm          129166 non-null  float64
 32  col          129166 non-null  float64
 33  adr          127802 non-null  object
 34  lat          129166 non-null  object
 35  long         129166 non-null  object
 36  dep          129166 non-null  object
 37  catr         129166 non-null  float64
 38  voie         119963 non-null  object
 39  v1           129166 non-null  float64
 40  v2           11271 non-null   object
 41  circ         129166 non-null  float64
 42  nbv          129166 non-null  float64
 43  vosp         129166 non-null  float64
 44  prof         129166 non-null  float64
 45  pr           129166 non-null  float64
 46  pr1          129166 non-null  float64
 47  plan         129166 non-null  float64
 48  lartpc       246 non-null     float64
 49  larrout      129166 non-null  float64
 50  surf         129166 non-null  float64
 51  infra        129166 non-null  float64
 52  situ         129166 non-null  float64
 53  vma          129166 non-null  float64
 54  nb_usagers   129169 non-null  int64
dtypes: float64(25), int64(19), object(11)
memory usage: 54.2+ MB

### Traitement des modalités incohérentes de certaines variables

In [33]:
base_final["sexe"].value_counts()

sexe
 1    86204
 2    39893
-1     3062
 3       10
Name: count, dtype: int64

Nous allons considérer les sexe clairement définit 1 et 2

In [34]:
# Filtrer la base pour ne garder que les valeurs valides (1 = Homme, 2 = Femme)
base_final = base_final[base_final["sexe"].isin([1, 2])]
base_final["sexe"].value_counts()

sexe
1    86204
2    39893
Name: count, dtype: int64

### Traitement de la variable heure

Extraire l'heure uniquement si hrmn est bien formatée (ex: '1530' → 15)

In [35]:
print("Valeurs uniques dans hrmn :")
base_final['hrmn'].unique()

Valeurs uniques dans hrmn :

array(['20:00', '18:30', '14:20', ..., '05:18', '04:54', nan],
      dtype=object)

In [36]:
# S'assurer que 'hrmn' est bien une colonne de chaînes
base_final['hrmn'] = base_final['hrmn'].astype(str)
# Remplacer les 'nan' chaînes par np.nan (au cas où)
base_final['hrmn'].replace('nan', np.nan, inplace=True)
# Isoler les valeurs valides
hrmn_valides = base_final['hrmn'].dropna()
# Distribution proportionnelle
distrib_hrmn = hrmn_valides.value_counts(normalize=True)
# Nombre de NaN à remplacer
n_nan = base_final['hrmn'].isna().sum()
# Tirage aléatoire proportionnel
tirage_proportionnel = np.random.choice(distrib_hrmn.index, size=n_nan, p=distrib_hrmn.values)
# Remplacement des NaN
base_final.loc[base_final['hrmn'].isna(), 'hrmn'] = tirage_proportionnel

C:\Users\sonex\AppData\Local\Temp\ipykernel_16816\1072064961.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  base_final['hrmn'].replace('nan', np.nan, inplace=True)

In [37]:
# Extraire l'heure uniquement si hrmn est bien formatée (ex: '1530' → 15)
base_final['heure'] = base_final["hrmn"].astype(str).str[:2].astype(int)

### Traitement des variables liées aux départements et aux communes

In [38]:
# Supprimer "CC_" au début de chaque valeur
base_final['com'] = base_final['com'].str.replace('CC_', '', regex=True)
# Calcul du mode de la variable 'com'
mode_com = base_final['com'].mode()[0]
# Remplir les valeurs manquantes avec le mode
base_final['com'].fillna(mode_com, inplace=True)
# Vérification
print(f"Le mode est {mode_com}, c'est la valeur utilisée pour remplir les valeurs manquantes.")
print('Le nombre de valeurs manquantes est :', base_final['com'].isna().sum())
# Extraire le département = les deux premiers caractères du code commune
base_final['dep'] = base_final['com'].astype(str).str[:2]
print('Les modalités liées aux départements et aux communes ont été traitées avec succès !')

Le mode est 75116, c'est la valeur utilisée pour remplir les valeurs manquantes.
Le nombre de valeurs manquantes est : 0
Les modalités liées aux départements et aux communes ont été traitées avec succès !

C:\Users\sonex\AppData\Local\Temp\ipykernel_16816\1043084141.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  base_final['com'].fillna(mode_com, inplace=True)

In [39]:
nb_lignes_avec_moins1 = (base_final == -1).any(axis=1).sum()
print(f"Nombre de lignes contenant au moins un -1 : {nb_lignes_avec_moins1}")
nb_lignes_sans_moins1 = (base_final != -1).all(axis=1).sum()
print(f"Nombre de lignes sans aucun -1 : {nb_lignes_sans_moins1}")
# Calcul du seuil (70% du nombre de colonnes)
seuil = 0.7 * base_final.shape[1]
# Compter combien de lignes ont au moins 70% de -1
nb_lignes_70pourcent_moins1 = (base_final == -1).sum(axis=1).ge(seuil).sum()
print(f"Nombre de lignes avec au moins 70% de -1 : {nb_lignes_70pourcent_moins1}")

Nombre de lignes contenant au moins un -1 : 126097
Nombre de lignes sans aucun -1 : 0
Nombre de lignes avec au moins 70% de -1 : 0

In [40]:
# Calcul du seuil (45 % du nombre de lignes)
seuil = 0.45 * base_final.shape[0]
# Identifier les colonnes ayant plus de 45% de -1
colonnes_45pourcent_moins1 = base_final.columns[(base_final == -1).sum(axis=0) > seuil]
# Afficher le nombre et les noms des colonnes concernées
print(f"Nombre de variables avec plus de 45% de -1 : {len(colonnes_45pourcent_moins1)}")
print("Colonnes concernées :", list(colonnes_45pourcent_moins1))
# Supprimer ces colonnes du DataFrame
base_final = base_final.drop(columns=colonnes_45pourcent_moins1)

Nombre de variables avec plus de 45% de -1 : 4
Colonnes concernées : ['secu3', 'locp', 'etatp', 'larrout']

### Traitement des variables trajet,secu1, secu2, secu3, locp, actp, etatp, senc, catv, obs, obsm , choc

In [41]:
base_final["trajet"] = base_final["trajet"].replace(0,-1)

In [42]:
# Pour reproductibilité des tirages aléatoires
np.random.seed(42)

# Étape 1 : Remplacer tous les -1 par NaN
base_final = base_final.replace(-1, np.nan)

# Colonnes à exclure
colonnes_exclues = ["v2", "lartpc", "occutc"]

# Étape 2 : Remplir les NaN proportionnellement aux autres modalités observées
for col in base_final.columns:
    if col not in colonnes_exclues:  # exclusion des colonnes
        if base_final[col].isna().any():
            # Récupérer les fréquences des valeurs non manquantes
            value_counts = base_final[col].value_counts(normalize=True)

            if not value_counts.empty:
                # Échantillonnage aléatoire selon les proportions observées
                num_nan = base_final[col].isna().sum()
                imputed_values = np.random.choice(value_counts.index, size=num_nan, p=value_counts.values)
                # Remplacer les NaN par les valeurs tirées
                base_final.loc[base_final[col].isna(), col] = imputed_values
            else:
                print(f"Colonne ignorée : '{col}' n'a aucune valeur non manquante, imputation impossible.")

print("Imputation terminée pour toutes les colonnes sauf celles exclues.")

Imputation terminée pour toutes les colonnes sauf celles exclues.

In [43]:
print((base_final["actp"] == -1).sum())  # combien de -1
print(base_final["actp"].isna().sum())  # combien de NaN dans actp
base_final["actp"].value_counts()

0
0

actp
-1    60099
0     56681
3      6833
9       642
1       610
5       434
2       263
B       244
A       120
4       116
6        26
8        19
7        10
Name: count, dtype: int64

In [44]:
# Pour reproductibilité
np.random.seed(42)

base_final["actp"] = base_final["actp"].replace("A", "10")
base_final["actp"] = base_final["actp"].replace("B", "11")

#  Nettoyer les variantes textuelles de -1
# Ex: ' -1 ', '- 1', etc. → -1
base_final["actp"] = base_final["actp"].astype(str).str.strip()  # supprime les espaces
base_final["actp"] = base_final["actp"].replace(r"^-+\s*1$", "-1", regex=True)  # ex: "- 1" → "-1"
base_final["actp"] = base_final["actp"].replace("-1", -1)  # convertir chaîne "-1" en entier -1

# Convertir en float pour permettre les NaN
base_final["actp"] = pd.to_numeric(base_final["actp"], errors='coerce')  # transforme ce qui reste non numérique en NaN
base_final["actp"] = base_final["actp"].astype(float)

#  Remplacer -1 par NaN
base_final["actp"] = base_final["actp"].replace(-1, np.nan)

# Imputation proportionnelle des NaN
if base_final["actp"].isna().any():
    value_counts = base_final["actp"].value_counts(normalize=True)
    num_nan = base_final["actp"].isna().sum()

    if len(value_counts) > 0:
        imputed_values = np.random.choice(value_counts.index, size=num_nan, p=value_counts.values)
        base_final.loc[base_final["actp"].isna(), "actp"] = imputed_values
    else:
        print("Aucune modalité observée dans 'actp' pour l’imputation.")

In [45]:
base_final["actp"].value_counts()

actp
0.0     108313
3.0      13049
9.0       1253
1.0       1110
5.0        840
2.0        507
11.0       460
10.0       243
4.0        222
6.0         46
8.0         37
7.0         17
Name: count, dtype: int64

### Création d'une variable âge et traitement de ses incohérences

In [46]:
base_final['age'] = base_final['an'] - base_final['an_nais']
print(base_final['age'].describe())  # moyenne, min, max, etc.

count    126097.000000
mean         37.908063
std          18.751929
min          -4.000000
25%          23.000000
50%          34.000000
75%          51.000000
max         232.000000
Name: age, dtype: float64

Notre base contient des individu de plus de 100 ans et -4ans , nous allons considerer ceux qui ont entre 10 ans et 100 ans

In [47]:
base_final = base_final[(base_final["age"] >= 10) & (base_final["age"] <= 100)]

### Traitement des incohérences de la variable vma

Compte tenu de la limite maximale de vitesse de circulation autorisée en France qui est de 130km/h, nous avons décider de garder un intervalle suivant 10 et 200.

In [48]:
base_final = base_final[(base_final["vma"] >= 10) & (base_final["vma"] <= 200)]

### Traitement des modalité de la variable "catv"

In [49]:
base_final["catv_group"] = base_final["catv"].replace({
    1: "Vélo / Cyclo", 2: "Vélo / Cyclo", 3: "Vélo / Cyclo", 30: "Vélo / Cyclo",
    31: "Moto / Scooter", 32: "Moto / Scooter", 33: "Moto / Scooter", 34: "Moto / Scooter",
    41: "3 roues motorisé", 42: "3 roues motorisé", 43: "3 roues motorisé",
    7: "VL", 10: "VU", 13: "PL", 14: "PL", 15: "PL", 16: "Tracteur routier", 17: "Tracteur routier",
    37: "Transport", 38: "Transport", 39: "Train / Tram", 40: "Train / Tram",
    20: "Spécial", 21: "Spécial", 35: "Quad", 36: "Quad",
    50: "EDP à moteur", 60: "EDP sans moteur", 80: "VAE",99: "Autre véhicule", 0: "Indéterminé"
})

In [50]:
base_final["catv_group"].value_counts()

catv_group
VL                  76096
Vélo / Cyclo        14753
Moto / Scooter      13923
VU                   8403
PL                   2298
EDP à moteur         1657
Transport            1309
3 roues motorisé      730
Tracteur routier      719
VAE                   574
Autre véhicule        508
Spécial               421
Train / Tram          257
Quad                  245
EDP sans moteur       227
Indéterminé           132
Name: count, dtype: int64

In [51]:
# Reclassification complète et cohérente de catv
base_final['catv'] = base_final['catv'].replace({
# Deux-roues non motorisés
    1: 'Deux-roues non motorisés',80: 'Deux-roues non motorisés',
# Deux-roues motorisés : # Cyclomoteur <50cc, Scooter <50cc, Moto ≤125cc, Moto >125cc, Trois-roues motorisé, Quad
    2: 'Deux-roues motorisés',30: 'Deux-roues motorisés', 31: 'Deux-roues motorisés', 60:'Deux-roues motorisés',
    33: 'Deux-roues motorisés',35: 'Deux-roues motorisés',36: 'Deux-roues motorisés',
# Véhicules légers (VP) : Voiturette; VL seul; Camping-car
    3: 'Véhicules légers',7: 'Véhicules légers', 34: 'Véhicules légers', 
# Véhicules utilitaires légers / pro 
    10: 'Véhicules légers pro',
# Poids lourds : PL 3.5-7.5T, PL > 7.5T, PL + remorque , Tracteur routier seul, Tracteur + semi-remorque
    13: 'Poids lourds',14: 'Poids lourds',15: 'Poids lourds',16: 'Poids lourds',17: 'Poids lourds',
# Véhicules agricoles / spéciaux : Engin spécial, Tracteur agricole, Engin de chantier
    20: 'Véhicules agricoles / spéciaux',21: 'Véhicules agricoles / spéciaux',50: 'Véhicules agricoles / spéciaux',
# Transport en commun : Autobus, Autocar, Train routier , Tramway
    37: 'Transport en commun',38: 'Transport en commun',39: 'Transport en commun',40: 'Transport en commun',
# Autres véhicules professionnels : Ambulance, Véhicule prioritaire (pompiers/police), Voiture de dépannage, Déneigeuse / voirie
    32: 'Véhicules professionnels spécialisés',41: 'Véhicules professionnels spécialisés',42: 'Véhicules professionnels spécialisés',
    43: 'Véhicules professionnels spécialisés',
    # Catégorie générique : Trottinette, gyropode, etc.
    99: 'Autre'
})

In [52]:
# Type de choc (choc)
base_final['choc'] = base_final['choc'].replace({0: 'Aucun',1: 'Avant',2: 'Avant',3: 'Avant',4: 'Arrière',5: 'Arrière', 6:'Arrière',
 7:'coté',8:'coté',9:'Multichoc' })
# Équipement de sécurité (secu1)
base_final['secu1'] = base_final['secu1'].replace({0: 'Aucun',1: 'Ceinture',2: 'Casque',3: 'Dispositif enfant',4: 'Gilet réfléchissant',
5: 'Airbag', 6: 'Gants',7: 'Gants + Airbag', 8: 'Autre',9: 'Autre'})
# Équipement de sécurité (secu2)
base_final['secu2'] = base_final['secu2'].replace({0: 'Aucun',1: 'Ceinture',2: 'Casque',3: 'Dispositif enfant',4: 'Gilet réfléchissant',
5: 'Airbag', 6: 'Gants',7: 'Gants + Airbag', 8: 'Autre',9: 'Autre'})

In [53]:
# Étape 3 : Remplacer les 0 par "Aucun" sauf sur la colonne heure
base_final.loc[:, base_final.columns != "heure"] = base_final.loc[:, base_final.columns != "heure"].replace(0, "Aucun")

C:\Users\sonex\AppData\Local\Temp\ipykernel_16816\549540975.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['Aucun' 'Aucun' 3.0 ... 'Aucun' 'Aucun' 'Aucun']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  base_final.loc[:, base_final.columns != "heure"] = base_final.loc[:, base_final.columns != "heure"].replace(0, "Aucun")
C:\Users\sonex\AppData\Local\Temp\ipykernel_16816\549540975.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[1.0 1.0 1.0 ... 1.0 1.0 1.0]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  base_final.loc[:, base_final.columns != "heure"] = base_final.loc[:, base_final.columns != "heure"].replace(0, "Aucun")
C:\Users\sonex\AppData\Local\Temp\ipykernel_16816\549540975.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['Aucun' 'Aucun' 'Aucun' ... 'Aucun' 'Aucun' 'Aucun']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  base_final.loc[:, base_final.columns != "heure"] = base_final.loc[:, base_final.columns != "heure"].replace(0, "Aucun")
C:\Users\sonex\AppData\Local\Temp\ipykernel_16816\549540975.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[2.0 2.0 2.0 ... 2.0 2.0 2.0]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  base_final.loc[:, base_final.columns != "heure"] = base_final.loc[:, base_final.columns != "heure"].replace(0, "Aucun")
C:\Users\sonex\AppData\Local\Temp\ipykernel_16816\549540975.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[1.0 9.0 2.0 ... 1.0 9.0 2.0]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  base_final.loc[:, base_final.columns != "heure"] = base_final.loc[:, base_final.columns != "heure"].replace(0, "Aucun")
C:\Users\sonex\AppData\Local\Temp\ipykernel_16816\549540975.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[1.0 1.0 1.0 ... 1.0 1.0 1.0]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  base_final.loc[:, base_final.columns != "heure"] = base_final.loc[:, base_final.columns != "heure"].replace(0, "Aucun")
C:\Users\sonex\AppData\Local\Temp\ipykernel_16816\549540975.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[nan nan nan ... nan nan nan]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  base_final.loc[:, base_final.columns != "heure"] = base_final.loc[:, base_final.columns != "heure"].replace(0, "Aucun")
C:\Users\sonex\AppData\Local\Temp\ipykernel_16816\549540975.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['Aucun' 'Aucun' 'Aucun' ... 'Aucun' 'Aucun' 'Aucun']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  base_final.loc[:, base_final.columns != "heure"] = base_final.loc[:, base_final.columns != "heure"].replace(0, "Aucun")
C:\Users\sonex\AppData\Local\Temp\ipykernel_16816\549540975.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[2.0 1.0 1.0 ... 2.0 2.0 1.0]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  base_final.loc[:, base_final.columns != "heure"] = base_final.loc[:, base_final.columns != "heure"].replace(0, "Aucun")
C:\Users\sonex\AppData\Local\Temp\ipykernel_16816\549540975.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['Aucun' 'Aucun' 1.0 ... 'Aucun' 'Aucun' 'Aucun']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  base_final.loc[:, base_final.columns != "heure"] = base_final.loc[:, base_final.columns != "heure"].replace(0, "Aucun")
C:\Users\sonex\AppData\Local\Temp\ipykernel_16816\549540975.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[173.0 'Aucun' 'Aucun' ... 16.0 'Aucun' 19.0]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  base_final.loc[:, base_final.columns != "heure"] = base_final.loc[:, base_final.columns != "heure"].replace(0, "Aucun")
C:\Users\sonex\AppData\Local\Temp\ipykernel_16816\549540975.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['Aucun' 'Aucun' 'Aucun' ... 'Aucun' 'Aucun' 'Aucun']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  base_final.loc[:, base_final.columns != "heure"] = base_final.loc[:, base_final.columns != "heure"].replace(0, "Aucun")
C:\Users\sonex\AppData\Local\Temp\ipykernel_16816\549540975.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[nan nan nan ... nan nan nan]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  base_final.loc[:, base_final.columns != "heure"] = base_final.loc[:, base_final.columns != "heure"].replace(0, "Aucun")
C:\Users\sonex\AppData\Local\Temp\ipykernel_16816\549540975.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['Aucun' 'Aucun' 'Aucun' ... 'Aucun' 'Aucun' 2.0]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  base_final.loc[:, base_final.columns != "heure"] = base_final.loc[:, base_final.columns != "heure"].replace(0, "Aucun")

In [54]:
base_final["choc"].value_counts()

choc
Avant        78384
Arrière      19922
coté         15086
Aucun         6896
Multichoc     1964
Name: count, dtype: int64

In [55]:

base_final['ordre_gravite'] = base_final['grav'].replace({1:'1',4:'2',3: '3',2: '4'})

## Gestion des doublons de la base finale

In [56]:
print("La base de données finale contient", sum(base_final.duplicated('Num_Acc')), "doublons")

La base de données finale contient 65865 doublons

In [57]:
print("La base de données finale contient", sum(base_final.duplicated()),'doublons purs')

La base de données finale contient 4 doublons purs

## Sauvegarde de la 1er base traitée

In [58]:
base_final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 122252 entries, 0 to 129168
Data columns (total 55 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Num_Acc        122252 non-null  int64
 1   id_vehicule    122252 non-null  object
 2   num_veh        122252 non-null  object
 3   place          122252 non-null  int64
 4   catu           122252 non-null  int64
 5   grav           122252 non-null  int64
 6   sexe           122252 non-null  int64
 7   an_nais        122252 non-null  float64
 8   trajet         122252 non-null  float64
 9   secu1          122252 non-null  object
 10  secu2          122252 non-null  object
 11  actp           122252 non-null  object
 12  senc           122252 non-null  object
 13  catv           122252 non-null  object
 14  obs            122252 non-null  object
 15  obsm           122252 non-null  object
 16  choc           122252 non-null  object
 17  manv           122252 non-null  object
 18  motor          122252 non-null  object
 19  occutc         1309 non-null    object
 20  jour           122252 non-null  float64
 21  mois           122252 non-null  float64
 22  an             122252 non-null  float64
 23  hrmn           122252 non-null  object
 24  lum            122252 non-null  float64
 25  com            122252 non-null  object
 26  agg            122252 non-null  float64
 27  int            122252 non-null  float64
 28  atm            122252 non-null  float64
 29  col            122252 non-null  float64
 30  adr            122252 non-null  object
 31  lat            122252 non-null  object
 32  long           122252 non-null  object
 33  dep            122252 non-null  object
 34  catr           122252 non-null  float64
 35  voie           122252 non-null  object
 36  v1             122252 non-null  object
 37  v2             10863 non-null   object
 38  circ           122252 non-null  float64
 39  nbv            122252 non-null  object
 40  vosp           122252 non-null  object
 41  prof           122252 non-null  float64
 42  pr             122252 non-null  object
 43  pr1            122252 non-null  object
 44  plan           122252 non-null  float64
 45  lartpc         232 non-null     object
 46  surf           122252 non-null  float64
 47  infra          122252 non-null  object
 48  situ           122252 non-null  float64
 49  vma            122252 non-null  float64
 50  nb_usagers     122252 non-null  int64
 51  heure          122252 non-null  int32
 52  age            122252 non-null  float64
 53  catv_group     122252 non-null  object
 54  ordre_gravite  122252 non-null  object
dtypes: float64(18), int32(1), int64(6), object(30)
memory usage: 51.8+ MB

In [59]:
base_final.to_csv("base_finale.csv")

# Récodification des modalités des variables sur une autre base

In [60]:
base_f=base_final.copy()

In [64]:
# Recode des variables qualitatives selon le fichier officiel ONISR
# À appliquer à base_f (ou base_finale) après importation des données

# Sexe
base_f['sexe'] = base_f['sexe'].replace({1: 'Homme',2: 'Femme'})

# Catégorie d’usager (catu)
base_f['catu'] = base_f['catu'].replace({1: 'Conducteur',2: 'Passager',3: 'Piéton'})

# Gravité (grav) = notre variable cible, nous ne la codons pas
#base_f['grav'] = base_f['grav'].replace({1: 'Indemne',2: 'Tué',3: 'Blessé hospitalisé',4: 'Blessé léger'})

# Trajet (trajet)
base_f['trajet'] = base_f['trajet'].replace({1: 'Domicile-travail',2: 'Domicile-école',3: 'Courses-achats',4: 'Utilisation professionnelle',
    5: 'Promenade-loisirs',9: 'Autre'})

# Lumière (lum)
base_f['lum'] = base_f['lum'].replace({1: 'Plein jour',2: 'Crépuscule ou aube',3: 'Nuit sans éclairage public',4: 'Nuit éclairage non allumé',
    5: 'Nuit éclairage allumé'})

# Conditions atmosphériques (atm)
base_f['atm'] = base_f['atm'].replace({1: 'Normale',2: 'Pluie légère',3: 'Pluie forte',4: 'Neige/grêle',5: 'Brouillard/fumée',
    6: 'Vent fort/tempête',7: 'Éblouissement',8: 'Temps couvert',9: 'Autre'})

# Manœuvre (manv)
base_f['manv'] = base_f['manv'].replace({1: 'Circulation normale',2: 'Circulation normale',
3: 'Circulation normale',4:'Manœuvres à faible vitesse',5:'Manœuvre complexe',6: 'Manœuvre complexe',7:'Dans le couloir bus',
9: 'Manœuvre complexe',10:'Manœuvre complexe',11:'Changement de voie',12: 'Changement de voie',8:'Dans le couloir bus',
13: 'Changement de voie',14:'Changement de voie',15:'Changement de voie',16:'Changement de voie',17: 'Manœuvre complexe',
18: 'Manœuvre complexe',19:'Traversée chaussée',20:'Stationnement/Arrêt',21:'Manœuvres à faible vitesse',22: 'Stationnement/Arrêt',
23: 'Stationnement/Arrêt',24:'Stationnement/Arrêt',25:'Manœuvres à faible vitesse',26:'Autre'})

# Lieu piéton (locp)
#base_f['locp'] = base_f['locp'].replace({1: '>50m passage piéton',2: '<50m passage piéton',
  #  3: 'Sur passage piéton sans feu',4: 'Sur passage piéton avec feu',5: 'Trottoir',6: 'Accotement',
  #  7: 'Refuge ou BAU',8: 'Contre-allée',9: 'Inconnu'})

# Action du piéton (actp)
base_f['actp'] = base_f['actp'].replace({1: 'Sens véhicule', 2: 'Sens inverse véhicule',3: 'Traversant',4: 'Masqué',
    5: 'Jouant/courant',6: 'Avec animal',9: 'Autre','A': 'Monte/descend véhicule','B': 'Inconnue'})

# État du piéton (etatp)
#base_f['etatp'] = base_f['etatp'].replace({1: 'Seul',2: 'Accompagné',3: 'En groupe'})

# agglomération
base_f['agg'] = base_f['agg'].replace({1:'Hors agglomération',2:'En agglomération'})

# Catégorie de route 
base_f["catr"] = base_f["catr"].replace({1: "Autoroute", 2: "Route nationale", 3: "Route Départemental", 4: "Voie Communales",
                                          5: "Hors réseau public", 6: "Parc de stationnement ouvert à la circulation publique", 
                                          7: "Routes de métropole urbaine", 9: "autre" })

# Profil en long décrit la déclivité de la route à l'endroit de l'accident 
base_f["prof"] = base_f["prof"].replace({1: "Plat", 2: "Pente", 3: "Sommet de côte" , 4: "Bas de côte"})

# Sens de circulation 
base_f["senc"] = base_f["senc"].replace({0: "Inconnu", 1: "PK ou PR ou numéro d’adresse postale croissant", 
                                         2: "PK ou PR ou numéro d’adresse postale décroissant", 3: "Absence de repère"})

In [65]:
base_f.shape

(122252, 55)

In [66]:
base_f.info()

<class 'pandas.core.frame.DataFrame'>
Index: 122252 entries, 0 to 129168
Data columns (total 55 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Num_Acc        122252 non-null  int64
 1   id_vehicule    122252 non-null  object
 2   num_veh        122252 non-null  object
 3   place          122252 non-null  int64
 4   catu           122252 non-null  object
 5   grav           122252 non-null  int64
 6   sexe           122252 non-null  object
 7   an_nais        122252 non-null  float64
 8   trajet         122252 non-null  object
 9   secu1          122252 non-null  object
 10  secu2          122252 non-null  object
 11  actp           122252 non-null  object
 12  senc           122252 non-null  object
 13  catv           122252 non-null  object
 14  obs            122252 non-null  object
 15  obsm           122252 non-null  object
 16  choc           122252 non-null  object
 17  manv           122252 non-null  object
 18  motor          122252 non-null  object
 19  occutc         1309 non-null    object
 20  jour           122252 non-null  float64
 21  mois           122252 non-null  float64
 22  an             122252 non-null  float64
 23  hrmn           122252 non-null  object
 24  lum            122252 non-null  object
 25  com            122252 non-null  object
 26  agg            122252 non-null  object
 27  int            122252 non-null  float64
 28  atm            122252 non-null  object
 29  col            122252 non-null  float64
 30  adr            122252 non-null  object
 31  lat            122252 non-null  object
 32  long           122252 non-null  object
 33  dep            122252 non-null  object
 34  catr           122252 non-null  object
 35  voie           122252 non-null  object
 36  v1             122252 non-null  object
 37  v2             10863 non-null   object
 38  circ           122252 non-null  float64
 39  nbv            122252 non-null  object
 40  vosp           122252 non-null  object
 41  prof           122252 non-null  object
 42  pr             122252 non-null  object
 43  pr1            122252 non-null  object
 44  plan           122252 non-null  float64
 45  lartpc         232 non-null     object
 46  surf           122252 non-null  float64
 47  infra          122252 non-null  object
 48  situ           122252 non-null  float64
 49  vma            122252 non-null  float64
 50  nb_usagers     122252 non-null  int64
 51  heure          122252 non-null  int32
 52  age            122252 non-null  float64
 53  catv_group     122252 non-null  object
 54  ordre_gravite  122252 non-null  object
dtypes: float64(12), int32(1), int64(4), object(38)
memory usage: 51.8+ MB

In [67]:
base_f.to_csv("base_f.csv", sep=";", index=False)